services:
  ubuntu: 
    image: ubuntu
    tty: true
    container_name: ubuntu
    volumes:
      - ./main.py:/main.py

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - test-tutorial

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3302:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

volumes:
  db-data:

networks:
  test-tutorial:
    external: true